const Status = {
  overview: 'Overview',
  noAuth: 'No overview viewing permission, contact platform administrator for authorization',
  noData: 'No data',
  running: 'Running',
  pending: 'Starting',
  stopping: 'Stopping',
  stopped: 'Stopped',
  operating: 'Operating',
  abnormal: 'Abnormal',
  one: 'One',
  memory: 'Memory',
  storage: 'Storage',
  apps: 'Apps',
  service: 'Services',
  container: 'Containers',
  volume: 'Volumes',
  snapshot: 'Snapshots',
  configuration: 'Service Configurations',
  mysql: 'MySQL Clusters',
  redis: 'Redis Clusters',
  zookeeper: 'Zookeeper Clusters',
  elasticsearch: 'ES Clusters',
  project: 'Project',
  personalProject: 'Personal Project',
  projectInfo: 'Project Information',
  projectDetail: 'Project Details',
  projectName: 'Project Name:',
  shared: 'Shared',
  personal: 'Personal',
  projecRoles: 'Project Roles:',
  personalProjectNoRoles: 'No roles in personal project',
  myBalance: 'My Balance:',
  projectBalance: 'Project Balance:',
  todayConsumption: 'Today Consumption:',
  allClusters: 'All Clusters',
  go: 'Go to view',
  accountInfo: 'Account Information',
  resourceQuotaOverview: 'Project & Cluster Resource Quotas Overview',
  setQuota: 'Set Quota',
  seeDetails: 'See Details',
  computingResource: 'Computing Resources',
  appManage: 'App Management',
  dbAndCache: 'Databases & Caches',
  todayClusterInfo: 'Today Cluster Information',
  createApp: 'Create App',
  createService: 'Create Service',
  createVolume: 'Create Volume',
  stopApp: 'Stop App',
  delService: 'Delete Service',
  delVolume: 'Delete Volume',
  updateApp: 'Update App',
  startApp: 'Start App',
  redeploy: 'Redeploy',
  sysStatus: 'System Status',
  app: 'App',
  serviceOnly: 'Service',
  containerOnly: 'Container',
  storageAndSnapshot: 'Storage & Snapshot',
  sharedStorage: 'Shared Storage',
  rbdStorage: 'Exclusive Storage',
  hostStorage: 'Local Storage',
  rbdStorageSnapshot: 'Exclusive Storage Snapshot',
  computingResourceUsage: 'Computing Resource Usage',
  computingResourceUsageTip: 'Show top three nodes by usage',
  showMasterNode: 'Show Master Node',
  nodeStatus: 'Node Status',
  nodesSum: 'Total Nodes',
  healthyNodesSum: 'Healthy Nodes',
  notEnabledNodesSum: 'Not Enabled Nodes',
  continued: 'Continued',
  microsecond: 'Microsecond',
  millisecond: 'Millisecond',
  second: 'Second',
  minute: 'Minute',
  hour: 'Hour',
  audit: 'Audit Log',
  seeMore: 'See More',
  unlimit: 'Unlimited',
  pipelines: 'Pipelines',
  stages: 'Stages',
  Dockerfile: 'Dockerfiles',
  cacheVolume: 'Cache Volumes',
  flow: 'Flows',
  stacks: 'Stacks',
  packages: 'Packages',
  projectResourceQuota: 'Project Resource Quota',
  appCenter: 'App Center',
  todayProjectInfo: 'Today Project Information',
  buildSuccessfully: 'Build Successfully',
  waitingForBuild: 'Waiting for Build',
  inApproval: 'In Approval',
  refusedToExecute: 'Refused to Execute',
  approvalTimeout: 'Approval Timeout',
  abort: 'Manually Stopped',
  pipelineStatusStatistics: 'Pipeline Execution Status Statistics',
  buildFailed: 'Build Failed',
  building: 'Building',
  serviceStatus: 'Service Status:',
  healthy: 'Healthy',
  harborProject: 'Image Repository',
  privateProject: 'Private Repository Group',
  privateImage: 'Private Image',
  publicHarbroProjects: 'Public Repository Groups',
  publicImages: 'Public Images',
  alarm: 'Alarm',
  noSysAlarm: 'No system alarms for now',
  svcNormal: 'Normal',
  svcWaring: 'Warning',
  svcNotInstall: 'Not Installed',
  svcAbnormal: 'Abnormal',
  svcStopped: 'Stopped',
  application: 'Application',
  notAvailable: 'N/A'
}

export default Status
